import {makeHarness,ok} from './test_helpers.mjs';

const h=makeHarness();
const {db,env,call,login}=h;
await login();
let x=await call('/api/me');
const mohsen=x.data.workspaces.find(w=>w.code==='MOHSEN');
const sehha=x.data.workspaces.find(w=>w.code==='SEHHA');
x=await call('/api/styles',{method:'POST',body:{orgId:mohsen.id,code:'ASSET-SECURITY',name:'Asset access test',garmentType:'JACKET',audience:'WOMEN',sizingMode:'STANDARD'}});
ok(x.r.status===201,'asset security fixture style created');
const styleId=x.data.id;
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/a9sAAAAASUVORK5CYII=';
x=await call(`/api/styles/${styleId}/assets`,{method:'POST',body:{role:'DETAIL',filename:'pixel.png',dataUrl:png,sourceKind:'STATIC_DEMO',rightsStatus:'APPROVED'}});
ok(x.r.status===201,'PNG is stored in R2');
const stored=db.prepare('SELECT source_kind,rights_status FROM assets WHERE id=?').get(x.data.id);
ok(stored.source_kind==='USER_UPLOAD'&&stored.rights_status==='USER_ASSERTED','client cannot elevate asset source or rights status');
const url=x.data.url;
x=await call(url,{cookieOverride:''});
ok(x.r.status===401,'asset URL requires authentication');
x=await call(url);
ok(x.r.status===200&&x.r.headers.get('content-type')==='image/png'&&x.r.headers.get('x-content-type-options')==='nosniff','authorized asset read uses safe image headers');
x=await call(`/api/styles/${styleId}/assets`,{method:'POST',body:{role:'DETAIL',filename:'fake.png',dataUrl:'data:image/png;base64,PGh0bWw+'}});
ok(x.r.status===415,'image MIME spoofing is rejected');
x=await call(`/api/styles/${styleId}/assets`,{method:'POST',body:{role:'DETAIL',filename:'script.svg',dataUrl:'data:image/svg+xml;base64,PHN2Zy8+'}});
ok(x.r.status===415,'SVG upload is rejected');
x=await call(`/api/styles/${styleId}/assets`,{method:'POST',body:{role:'DETAIL',filename:'bad.png',dataUrl:'data:image/png;base64,@@@'}});
ok(x.r.status===400,'invalid base64 returns a client error');
const adminId=db.prepare("SELECT id FROM users WHERE email='dev@sehha.local'").get().id;
const ts=new Date().toISOString();
db.prepare('INSERT INTO styles(id,org_id,code,name,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run('cross-style',sehha.id,'CROSS-STYLE','Other workspace',adminId,ts,ts);
db.prepare('INSERT INTO assets(id,style_id,role,filename,stored_name,mime_type,created_at) VALUES(?,?,?,?,?,?,?)').run('cross-asset','cross-style','DETAIL','cross.png','cross.png','image/png',ts);
await env.UPLOADS.put('cross.png',new Uint8Array([137,80,78,71,13,10,26,10]),{httpMetadata:{contentType:'image/png'}});
x=await call('/api/auth/login',{method:'POST',body:{email:'mohsen@mohsen.local',password:env.MOHSEN_BOOTSTRAP_PASSWORD},cookieOverride:''});
const specialistCookie=(x.r.headers.get('set-cookie')||'').split(';')[0];
x=await call('/uploads/cross.png',{cookieOverride:specialistCookie});
ok(x.r.status===403,'asset read enforces tenant isolation');
console.log('ASSET_SECURITY_PASS');
