import {makeHarness,ok} from './test_helpers.mjs';
const {db,call,login}=makeHarness();await login();let x=await call('/api/me');const org=x.data.workspaces.find(w=>w.code==='MOHSEN');
x=await call('/api/styles',{method:'POST',body:{orgId:org.id,code:'COST-019',name:'Material Cost Analytics',garmentType:'JACKET',audience:'WOMEN',sizingMode:'STANDARD'}});const id=x.data.id,uid=db.prepare("SELECT id FROM users WHERE email='dev@sehha.local'").get().id,ts=new Date().toISOString();
const frozen={style:{id,org_id:org.id,code:'COST-019',name:'Material Cost Analytics'},sizeBands:[],colorways:[],measurements:[],bom:[],operations:[],patternPieces:[],patternLinks:[],requirements:[],assets:[],dna:[],gradingRules:[],annotations:[],samples:[],costSheets:[]};
db.prepare("INSERT INTO style_releases(id,style_id,release_no,release_type,status,source_version_no,template_key,gate_json,manifest_json,snapshot_json,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run('rel19',id,1,'PRODUCTION','RELEASED',1,'mohsen_nexz_20p','{}','{}',JSON.stringify(frozen),uid,ts);
db.prepare("INSERT INTO cost_sheets(id,style_id,version_no,name,currency,status,labor_cost,overhead_pct,waste_pct,note,created_by,approved_by,created_at,updated_at,approved_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run('cost19',id,1,'Frozen Cost','EGP','APPROVED',25,10,5,null,uid,uid,ts,ts,ts);
db.prepare("INSERT INTO cost_lines(id,cost_sheet_id,source_type,source_ref,description,qty,unit,unit_cost,waste_pct,line_total,note,created_by,updated_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run('cl19','cost19','BOM','FABRIC','Main fabric',1.8,'m',100,5,189,null,uid,uid,ts,ts);
x=await call(`/api/styles/${id}/production-lots`,{method:'POST',body:{releaseNo:1,lotCode:'LOT-COST',plannedQty:100}});ok(x.r.status===201,'lot created with frozen priced basis');const lid=x.data.lot.id;ok(Math.abs(x.data.planning.materialRequirements[0].plannedMaterialCost-18900)<0.001,'planned material cost uses frozen gross requirement × unit cost');
x=await call(`/api/styles/${id}/production-lots/${lid}/reconciliation/start`,{method:'POST',body:{expectedVersion:1}});x=await call(`/api/styles/${id}/production-lots/${lid}/reconciliation/output`,{method:'PATCH',body:{actualOutputQty:96,expectedVersion:2}});const key=x.data.reconciliation.materials[0].materialKey;x=await call(`/api/styles/${id}/production-lots/${lid}/material-usage`,{method:'POST',body:{materialKey:key,actualQty:185,scrapQty:4,expectedVersion:3}});ok(x.r.status===201&&x.data.reconciliation.cost.available,'material cost analytics available from frozen unit cost');const c=x.data.reconciliation.cost;ok(c.currency==='EGP'&&Math.abs(c.plannedMaterialCost-18900)<0.001,'planned material cost is 18,900 EGP');ok(Math.abs(c.actualMaterialCost-18500)<0.001&&Math.abs(c.materialCostVariance+400)<0.001,'actual material cost and -400 EGP variance calculated');ok(Math.abs(c.actualMaterialCostPerGoodUnit-(18500/96))<0.001,'actual material cost per good unit uses actual output');
// Reprice the approved Cost Sheet after lot creation; historical lot analytics must remain frozen.
db.prepare("UPDATE cost_lines SET unit_cost=999 WHERE id='cl19'").run();x=await call(`/api/styles/${id}/production-lots/${lid}`);ok(Math.abs(x.data.reconciliation.cost.actualMaterialCost-18500)<0.001,'later cost sheet edit does not reprice historical lot analytics');ok(x.data.reconciliation.cost.scope==='MATERIAL_ONLY','analytics scope explicitly remains material-only');
console.log('BATCH19_INTEGRATION_PASS');
