import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),db=new DatabaseSync(':memory:');
for(const f of ['0001_init.sql','0002_ai_review_pattern.sql','0003_mohsen_master_bilingual.sql','0004_pattern_intelligence_grading.sql','0005_release_workflow.sql','0006_factory_collaboration.sql','0007_requirements_matrix.sql'])db.exec(readFileSync(resolve(root,'migrations',f),'utf8'));
const ts=new Date().toISOString();db.prepare("INSERT INTO styles(id,org_id,code,name,garment_type,audience,sizing_mode,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run('s1','o1','LEG-10','Legacy Preview10','JACKET','WOMEN','STANDARD','DRAFT','u1',ts,ts);db.prepare("INSERT INTO measurements(id,style_id,code,name,value,unit,provenance,state,sort_order) VALUES(?,?,?,?,?,?,?,?,?)").run('m1','s1','A','Length',57,'cm','USER_CONFIRMED','LOCKED',1);db.prepare("INSERT INTO style_versions(id,style_id,version_no,label,snapshot_json,created_by,created_at) VALUES(?,?,?,?,?,?,?)").run('v1','s1',1,'Legacy V1','{}','u1',ts);
for(const f of ['0008_sample_fit_validation.sql','0009_costing_consumption.sql','0010_production_quality.sql'])db.exec(readFileSync(resolve(root,'migrations',f),'utf8'));
const schema=db.prepare("SELECT value FROM app_meta WHERE key='schema_version'").get().value;if(schema!=='12')throw new Error('schema != 12');if(!db.prepare("SELECT id FROM styles WHERE id='s1'").get())throw new Error('style lost');if(db.prepare("SELECT state FROM measurements WHERE id='m1'").get().state!=='LOCKED')throw new Error('locked POM lost');if(!db.prepare("SELECT id FROM style_versions WHERE id='v1'").get())throw new Error('version lost');for(const t of ['sample_rounds','sample_measurements','cost_sheets','cost_lines','production_lots','quality_checks','production_defects'])db.prepare(`SELECT count(*) c FROM ${t}`).get();console.log('BATCH13_UPGRADE_PASS schema=12 legacyStyle=1 lockedPom=1 version=1 newTables=7');
