import {makeHarness,ok} from './test_helpers.mjs';
const {db,call,login}=makeHarness();await login();let x=await call('/api/me');const org=x.data.workspaces.find(w=>w.code==='MOHSEN');
x=await call('/api/styles',{method:'POST',body:{orgId:org.id,code:'FREEZE-015',name:'Frozen Planning Basis Test',garmentType:'JACKET',audience:'WOMEN',sizingMode:'STANDARD'}});const id=x.data.id;const uid=db.prepare("SELECT id FROM users WHERE email='dev@sehha.local'").get().id,ts=new Date().toISOString();
// Source version 1 and production release
const frozen={style:{id,org_id:org.id,code:'FREEZE-015',name:'Frozen Planning Basis Test'},sizeBands:[],colorways:[],measurements:[],bom:[],operations:[],patternPieces:[],patternLinks:[],requirements:[],assets:[],dna:[],gradingRules:[],annotations:[],samples:[],costSheets:[]};
db.prepare("INSERT INTO style_releases(id,style_id,release_no,release_type,status,source_version_no,template_key,gate_json,manifest_json,snapshot_json,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run('rel15',id,1,'PRODUCTION','RELEASED',1,'mohsen_nexz_20p','{}','{}',JSON.stringify(frozen),uid,ts);
function addCost(sheet,line,qty,waste,approvedAt){db.prepare("INSERT INTO cost_sheets(id,style_id,version_no,name,currency,status,labor_cost,overhead_pct,created_by,approved_by,created_at,updated_at,approved_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(sheet,id,1,sheet,'EGP','APPROVED',20,10,uid,uid,approvedAt,approvedAt,approvedAt);db.prepare("INSERT INTO cost_lines(id,cost_sheet_id,source_type,source_ref,description,qty,unit,unit_cost,waste_pct,line_total,created_by,updated_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(line,sheet,'BOM','B01','Fabric',qty,'m',100,waste,qty*100*(1+waste/100),uid,uid,approvedAt,approvedAt)}
addCost('COST-A','LINE-A',1.5,0,'2026-10-01T10:00:00Z');
x=await call(`/api/styles/${id}/production-lots`,{method:'POST',body:{releaseNo:1,lotCode:'LOT-FROZEN',plannedQty:100}});ok(x.r.status===201&&x.data.planning.materialBasis.costSheetId==='COST-A','lot captures approved cost basis at creation');const lid=x.data.lot.id,shaA=x.data.planning.materialBasisSha256;let mr=x.data.planning.materialRequirements[0];ok(mr.netRequired===150,'initial material requirement uses COST-A consumption');
// Newer approved costing must not silently rewrite existing lot plan
addCost('COST-B','LINE-B',2.0,10,'2026-10-02T10:00:00Z');
x=await call(`/api/styles/${id}/production-lots/${lid}/plan`);ok(x.data.planning.materialBasis.costSheetId==='COST-A'&&x.data.planning.materialBasisSha256===shaA,'new approved costing does not alter existing lot basis');ok(x.data.planning.materialRequirements[0].netRequired===150,'existing lot material requirement remains historically stable');
// Explicit rebase switches basis and hash
x=await call(`/api/styles/${id}/production-lots/${lid}/plan/rebase`,{method:'POST',body:{}});ok(x.r.status===200&&x.data.planning.materialBasis.costSheetId==='COST-B','explicit rebase adopts latest approved costing');ok(x.data.planning.materialBasisSha256!==shaA,'rebase changes planning basis SHA256');mr=x.data.planning.materialRequirements[0];ok(mr.netRequired===200&&Math.abs(mr.grossRequired-220)<1e-9,'rebased requirements use new explicit consumption/waste');
// release after QC; rebase becomes immutable
x=await call(`/api/styles/${id}/production-lots/${lid}/checks`,{method:'POST',body:{checkType:'FINAL',status:'PASS'}});ok(x.r.status===201&&x.data.gate.ready,'lot ready when planning + QC pass');x=await call(`/api/styles/${id}/production-lots/${lid}/release`,{method:'POST',body:{}});ok(x.r.status===200,'lot released');x=await call(`/api/styles/${id}/production-lots/${lid}/plan/rebase`,{method:'POST',body:{}});ok(x.r.status===409,'released lot rejects planning rebase');x=await call(`/api/audit?orgId=${org.id}`);ok(x.data.items.some(a=>a.entity_type==='PRODUCTION_LOT'&&a.action==='PLAN_REBASE'),'planning rebase is audited');
console.log('BATCH15_INTEGRATION_PASS');
