import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import worker from '../src/worker.js';
const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'..');
const realConsoleError=console.error;console.error=(...args)=>{if(process.env.VERBOSE_TEST==='1')realConsoleError(...args)};
const db=new DatabaseSync(':memory:');for(const f of ['0001_init.sql','0002_ai_review_pattern.sql','0003_mohsen_master_bilingual.sql','0004_pattern_intelligence_grading.sql','0005_release_workflow.sql','0006_factory_collaboration.sql','0007_requirements_matrix.sql','0008_sample_fit_validation.sql','0009_costing_consumption.sql','0010_production_quality.sql','0011_production_planning.sql','0012_frozen_planning_basis.sql','0013_factory_operation_execution.sql','0014_reconciliation_concurrency.sql','0015_full_actual_cost.sql','0016_engineering_foundation.sql'])db.exec(readFileSync(resolve(root,'migrations',f),'utf8'));
class D1Mock{constructor(db){this.db=db}prepare(sql){const st=this.db.prepare(sql);return{bind:(...args)=>{const vals=args.map(v=>v===undefined?null:v);return{first:()=>st.get(...vals)||null,all:()=>({results:st.all(...vals)}),run:()=>{const r=st.run(...vals);return{success:true,meta:{changes:Number(r.changes||0)}}}}}}}}
class R2Object{constructor(bytes,meta={}){this.bytes=bytes;this.meta=meta;this.httpEtag='test-etag';this.body=bytes}async arrayBuffer(){return this.bytes.buffer.slice(this.bytes.byteOffset,this.bytes.byteOffset+this.bytes.byteLength)}writeHttpMetadata(h){if(this.meta?.httpMetadata?.contentType)h.set('content-type',this.meta.httpMetadata.contentType)}}
class R2Mock{constructor(){this.map=new Map()}async put(k,bytes,meta){this.map.set(k,new R2Object(new Uint8Array(bytes),meta));return{}}async get(k){return this.map.get(k)||null}}
const demo=readFileSync(resolve(root,'public','demo_jk001_reference.png'));const STATIC={fetch:async input=>{const raw=typeof input==='string'?input:(input instanceof URL?input.href:input.url);const u=new URL(raw);if(u.pathname==='/demo_jk001_reference.png')return new Response(demo,{headers:{'content-type':'image/png'}});return new Response('static',{status:200})}};
const env={DB:new D1Mock(db),UPLOADS:new R2Mock(),STATIC,SESSION_SECRET:'batch09-secret',DEV_BOOTSTRAP_PASSWORD:'DevOnly!234',MOHSEN_BOOTSTRAP_PASSWORD:'MohsenOnly!234',LICENSE_MODE:'development'};let cookie='';
async function call(path,{method='GET',body,cookieOverride}={}){const headers={};if(body!==undefined)headers['content-type']='application/json';const c=cookieOverride===undefined?cookie:cookieOverride;if(c)headers.cookie=c;const r=await worker.fetch(new Request('http://local'+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),env);const ct=r.headers.get('content-type')||'';const data=ct.includes('json')?await r.json():await r.text();return{r,data}}
function ok(c,m){if(!c)throw new Error('ASSERT: '+m);console.log('PASS',m)}
await call('/api/me',{cookieOverride:''});let x=await call('/api/auth/login',{method:'POST',body:{email:'dev@sehha.local',password:env.DEV_BOOTSTRAP_PASSWORD},cookieOverride:''});ok(x.r.status===200,'developer login');cookie=(x.r.headers.get('set-cookie')||'').split(';')[0];
x=await call('/api/health');ok(x.r.status===200&&x.data.version==='0.21.0-cloudflare'&&x.data.schemaVersion==='18','Preview 21 health/schema');x=await call('/api/me');const mohsen=x.data.workspaces.find(w=>w.code==='MOHSEN');
// Empty dress intake
x=await call('/api/styles',{method:'POST',body:{orgId:mohsen.id,code:'MFD-DR-009',name:'فستان تطوير Blueprint',garmentType:'DRESS',audience:'WOMEN',sizingMode:'STANDARD',baseSize:'M'}});ok(x.r.status===201,'Dress style created');const id=x.data.id;
x=await call(`/api/styles/${id}/blueprint`);ok(x.r.status===200&&x.data.profile.family==='DRESS'&&x.data.numericValuesGenerated===false,'Dress blueprint is suggestion-only');ok(x.data.measurements.every(m=>m.value===null)&&x.data.patterns.every(p=>p.qty===null&&p.grainline===null),'Blueprint contains no generated numeric/pattern production facts');ok(x.data.dna.some(d=>d.key==='neckline')&&x.data.patterns.some(p=>p.semanticCode==='SKIRT_PANEL'),'Dress blueprint structure is profile-specific');
x=await call(`/api/styles/${id}/intake-readiness`);const initial=x.data.score;ok(x.r.status===200&&initial<50&&!x.data.readyForDevelopment,'Empty intake reports low readiness');ok(x.data.requiredMissing.some(c=>c.key==='REFERENCE')&&x.data.requiredMissing.some(c=>c.key==='POM'),'Readiness exposes missing required structure');
// Existing human fact must survive skeleton application.
x=await call(`/api/styles/${id}/dna`,{method:'POST',body:{fieldKey:'fit',label:'القصة / Fit',value:'A-line approved design intent',provenance:'USER_CONFIRMED',state:'APPROVED'}});ok(x.r.status===200,'Human-confirmed fit saved before blueprint');
x=await call(`/api/styles/${id}/apply-blueprint`,{method:'POST',body:{sections:['dna','measurements','patterns','bom','operations']}});ok(x.r.status===200&&x.data.productionFactsGenerated===false,'Blueprint skeleton applied without production facts');ok(x.data.counts.measurements>0&&x.data.counts.patterns>0&&x.data.counts.operations>0,'Skeleton creates missing development structure');
x=await call(`/api/styles/${id}`);const snap=x.data;const fit=snap.dna.find(d=>d.field_key==='fit');ok(fit.value_text==='A-line approved design intent'&&fit.provenance==='USER_CONFIRMED'&&fit.state==='APPROVED','Blueprint never overwrites existing human fact');ok(snap.measurements.filter(m=>m.code.startsWith('BP-')).every(m=>m.value==null&&m.provenance==='TEMPLATE_SUGGESTION'&&m.state==='TBC'),'Applied POM skeleton remains value-null TBC');ok(snap.patternPieces.filter(p=>p.code.startsWith('BP-')).every(p=>p.qty==null&&p.grainline==null&&p.provenance==='TEMPLATE_SUGGESTION'),'Applied pattern skeleton has no qty/grain invention');ok(snap.bom.filter(b=>b.code.startsWith('BP-')).every(b=>b.specification==null&&b.qty==null&&b.status==='TBC'),'Applied BOM skeleton has no material/spec/qty invention');ok(snap.operations.every(o=>o.provenance==='TEMPLATE_SUGGESTION'&&o.state==='TBC'),'Operation skeleton stays unapproved');
// Idempotent missing-only apply.
x=await call(`/api/styles/${id}/apply-blueprint`,{method:'POST',body:{sections:['dna','measurements','patterns','bom','operations']}});ok(Object.values(x.data.counts).every(v=>v===0),'Repeated blueprint application is idempotent');
// Readiness improves structurally but reference is still missing.
x=await call(`/api/styles/${id}/intake-readiness`);ok(x.data.score>initial&&!x.data.readyForDevelopment&&x.data.requiredMissing.length===1&&x.data.requiredMissing[0].key==='REFERENCE','Skeleton improves intake readiness without faking missing evidence');
// Add evidence => intake structurally ready, but production still fails because TBC suggestions require human confirmation.
const dataUrl='data:image/png;base64,'+demo.toString('base64');x=await call(`/api/styles/${id}/assets`,{method:'POST',body:{filename:'dress-ref.png',dataUrl,role:'HERO',rightsStatus:'USER_ASSERTED'}});ok(x.r.status===201,'Reference evidence added');x=await call(`/api/styles/${id}/intake-readiness`);ok(x.data.readyForDevelopment===true&&x.data.score===100,'Intake becomes structurally ready after evidence');
x=await call(`/api/styles/${id}/release-gate?type=PRODUCTION`);ok(x.r.status===200&&x.data.ready===false&&x.data.blockers.some(b=>['POM_UNAPPROVED','DNA_TBC','BOM_TBC','OPERATIONS_UNAPPROVED'].includes(b.code)),'Production remains fail-closed on blueprint TBC rows');
// Dynamic output remains valid and garment-specific.
x=await call(`/api/styles/${id}/output?profile=mohsen_techpack`);ok(x.r.status===200&&(x.data.match(/class="tp-page/g)||[]).length===20,'Blueprint dress still renders 20-page master');ok(/>Dress</.test(x.data)&&!/Morfok|Men&#39;s Pants/i.test(x.data),'Dress output has no cross-garment leakage');
// Islamic Wear blueprint has its own evidence and embellishment/opening semantics.
x=await call('/api/styles',{method:'POST',body:{orgId:mohsen.id,code:'MFD-IW-009',name:'خمار تجريبي',garmentType:'ISLAMIC_WEAR',audience:'WOMEN',sizingMode:'WEIGHT_BANDS'}});const iw=x.data.id;x=await call(`/api/styles/${iw}/blueprint`);ok(x.data.profile.family==='ISLAMIC_WEAR'&&x.data.dna.some(d=>d.key==='coverage')&&x.data.dna.some(d=>d.key==='embellishment'),'Islamic Wear blueprint exposes coverage/embellishment semantics');ok(x.data.evidence.some(e=>e.role==='DETAIL'),'Islamic Wear blueprint requests detail evidence');
console.log('BATCH09_INTEGRATION_PASS');
