import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import worker from '../src/worker.js';
const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'..');
const realConsoleError=console.error;console.error=(...args)=>{if(process.env.VERBOSE_TEST==='1')realConsoleError(...args)};
const migrations=['0001_init.sql','0002_ai_review_pattern.sql','0003_mohsen_master_bilingual.sql','0004_pattern_intelligence_grading.sql','0005_release_workflow.sql','0006_factory_collaboration.sql','0007_requirements_matrix.sql','0008_sample_fit_validation.sql','0009_costing_consumption.sql','0010_production_quality.sql','0011_production_planning.sql','0012_frozen_planning_basis.sql','0013_factory_operation_execution.sql','0014_reconciliation_concurrency.sql','0015_full_actual_cost.sql','0016_engineering_foundation.sql','0017_human_experience.sql','0018_human_qc.sql','0019_human_store.sql'];
const db=new DatabaseSync(':memory:');for(const f of migrations)db.exec(readFileSync(resolve(root,'migrations',f),'utf8'));
class D1Mock{constructor(db){this.db=db}prepare(sql){const st=this.db.prepare(sql);return{bind:(...args)=>{const vals=args.map(v=>v===undefined?null:v);return{first:()=>st.get(...vals)||null,all:()=>({results:st.all(...vals)}),run:()=>{const r=st.run(...vals);return{success:true,meta:{changes:Number(r.changes||0)}}}}}}}}
class R2Object{constructor(bytes,meta={}){this.bytes=bytes;this.meta=meta;this.httpEtag='test';this.body=bytes}async arrayBuffer(){return this.bytes.buffer.slice(this.bytes.byteOffset,this.bytes.byteOffset+this.bytes.byteLength)}writeHttpMetadata(h){if(this.meta?.httpMetadata?.contentType)h.set('content-type',this.meta.httpMetadata.contentType)}}
class R2Mock{constructor(){this.map=new Map()}async put(k,bytes,meta){this.map.set(k,new R2Object(new Uint8Array(bytes),meta));return{}}async get(k){return this.map.get(k)||null}}
const demo=readFileSync(resolve(root,'public','demo_jk001_reference.png'));const STATIC={fetch:async()=>new Response('static')};
const env={DB:new D1Mock(db),UPLOADS:new R2Mock(),STATIC,SESSION_SECRET:'b10-secret',DEV_BOOTSTRAP_PASSWORD:'DevOnly!234',MOHSEN_BOOTSTRAP_PASSWORD:'MohsenOnly!234',LICENSE_MODE:'development'};let cookie='';
async function call(path,{method='GET',body,cookieOverride}={}){const headers={};if(body!==undefined)headers['content-type']='application/json';const c=cookieOverride===undefined?cookie:cookieOverride;if(c)headers.cookie=c;const r=await worker.fetch(new Request('http://local'+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),env);const ct=r.headers.get('content-type')||'';const data=ct.includes('json')?await r.json():await r.text();return{r,data}}
function ok(c,m){if(!c)throw new Error('ASSERT: '+m);console.log('PASS',m)}
let x=await call('/api/auth/login',{method:'POST',body:{email:'dev@sehha.local',password:env.DEV_BOOTSTRAP_PASSWORD},cookieOverride:''});ok(x.r.status===200,'developer login');cookie=(x.r.headers.get('set-cookie')||'').split(';')[0];
x=await call('/api/health');ok(x.r.status===200&&x.data.version==='0.21.0-cloudflare'&&x.data.schemaVersion==='21','Preview 21 health/schema');
x=await call('/api/me');const mohsen=x.data.workspaces.find(w=>w.code==='MOHSEN');
x=await call('/api/styles',{method:'POST',body:{orgId:mohsen.id,code:'MFD-DR-010',name:'فستان Requirements Matrix',garmentType:'DRESS',audience:'WOMEN',sizingMode:'STANDARD',baseSize:'M'}});ok(x.r.status===201,'test style created');const id=x.data.id;
// Matrix absent => backwards compatible; no requirement blocker yet.
x=await call(`/api/styles/${id}/requirements`);ok(x.r.status===200&&!x.data.gate.matrixExists&&x.data.gate.ready,'requirements are opt-in and absent matrix does not block legacy style');
x=await call(`/api/styles/${id}/requirements/sync-blueprint`,{method:'POST',body:{}});ok(x.r.status===200&&x.data.created>5&&x.data.items.some(r=>r.req_key==='CORE_REFERENCE'&&r.applicability==='REQUIRED'),'blueprint requirements synchronized with core required rows');ok(x.data.items.some(r=>r.req_key.startsWith('DNA:')&&r.applicability==='OPTIONAL'),'detailed blueprint semantics default OPTIONAL');
x=await call(`/api/styles/${id}/requirements`);ok(x.data.gate.blockerCount===5&&!x.data.gate.ready,'empty style has five required core blockers');
// Blueprint skeleton + reference auto-satisfy the five structural core requirements.
x=await call(`/api/styles/${id}/apply-blueprint`,{method:'POST',body:{sections:['dna','measurements','patterns','bom','operations']}});ok(x.r.status===200,'blueprint skeleton applied');const dataUrl='data:image/png;base64,'+demo.toString('base64');x=await call(`/api/styles/${id}/assets`,{method:'POST',body:{filename:'ref.png',dataUrl,role:'HERO',rightsStatus:'USER_ASSERTED'}});ok(x.r.status===201,'reference asset uploaded');
x=await call(`/api/styles/${id}/requirements`);ok(x.data.gate.blockerCount===0&&x.data.gate.ready&&x.data.gate.items.filter(r=>r.req_key.startsWith('CORE_')).every(r=>r.effectiveStatus==='SATISFIED'),'core required rows auto-satisfied from actual frozen style structure');
// Required custom rule blocks; optional open does not.
x=await call(`/api/styles/${id}/requirements`,{method:'POST',body:{reqKey:'CUSTOM:LINING_APPROVAL',category:'CONSTRUCTION',label:'اعتماد قرار البطانة',labelEn:'Lining decision approval',applicability:'REQUIRED',status:'OPEN',linkedRef:'DNA:lining'}});ok(x.r.status===200,'custom required requirement created');
x=await call(`/api/styles/${id}/requirements`,{method:'POST',body:{reqKey:'CUSTOM:POCKET_DETAIL',category:'CONSTRUCTION',label:'تفصيلة الجيب',labelEn:'Pocket detail',applicability:'OPTIONAL',status:'OPEN',linkedRef:'PATTERN:POCKET'}});ok(x.r.status===200,'custom optional requirement created');
x=await call(`/api/styles/${id}/requirements`);ok(x.data.gate.blockerCount===1&&x.data.gate.optionalOpenCount>0&&x.data.gate.blockers[0].reqKey==='CUSTOM:LINING_APPROVAL','only REQUIRED OPEN blocks requirements gate');
x=await call(`/api/styles/${id}/release-gate?type=PRODUCTION`);ok(x.r.status===200&&x.data.blockers.some(b=>b.code==='REQUIREMENTS_OPEN'&&b.items.includes('CUSTOM:LINING_APPROVAL')),'Production gate integrates requirements blocker');
// Freeze a version while the human decision is OPEN.
x=await call(`/api/styles/${id}/versions`,{method:'POST',body:{label:'Before requirement decision'}});ok(x.r.status===201&&x.data.versionNo===1,'version freezes requirements state');const frozen=JSON.parse(db.prepare('SELECT snapshot_json FROM style_versions WHERE style_id=? AND version_no=1').get(id).snapshot_json);ok(frozen.requirements.some(r=>r.req_key==='CUSTOM:LINING_APPROVAL'&&r.status==='OPEN'&&r.applicability==='REQUIRED'),'frozen version contains original requirement decision');
// Waiver/NA decisions require notes.
x=await call(`/api/styles/${id}/requirements/${encodeURIComponent('CUSTOM:LINING_APPROVAL')}`,{method:'PATCH',body:{status:'WAIVED',note:''}});ok(x.r.status===400,'WAIVED requires explicit decision note');
x=await call(`/api/styles/${id}/requirements/${encodeURIComponent('CUSTOM:LINING_APPROVAL')}`,{method:'PATCH',body:{status:'WAIVED',note:'No lining in approved design direction'}});ok(x.r.status===200&&x.data.gate.blockerCount===0,'documented waiver closes required blocker');
const optionalKey=x=>x.req_key.startsWith('DNA:')?x.req_key:null;x=await call(`/api/styles/${id}/requirements`);const dnaOpt=x.data.items.find(r=>r.req_key.startsWith('DNA:'));ok(Boolean(dnaOpt),'blueprint optional requirement available');x=await call(`/api/styles/${id}/requirements/${encodeURIComponent(dnaOpt.req_key)}`,{method:'PATCH',body:{applicability:'NOT_APPLICABLE',note:'Not applicable to this approved model'}});ok(x.r.status===200&&x.data.item.applicability==='NOT_APPLICABLE','NOT_APPLICABLE human decision saved');
// Current working changed; frozen version remains immutable.
x=await call(`/api/styles/${id}`);ok(x.data.requirements.find(r=>r.req_key==='CUSTOM:LINING_APPROVAL').status==='WAIVED','working requirements reflect new decision');const frozenAgain=JSON.parse(db.prepare('SELECT snapshot_json FROM style_versions WHERE style_id=? AND version_no=1').get(id).snapshot_json);ok(frozenAgain.requirements.find(r=>r.req_key==='CUSTOM:LINING_APPROVAL').status==='OPEN','frozen version remains immutable after working decision changes');
x=await call(`/api/styles/${id}/release-gate?type=PRODUCTION`);ok(!x.data.blockers.some(b=>b.code==='REQUIREMENTS_OPEN'),'requirements blocker cleared while other production integrity gates remain independent');
// Development variants inherit requirement semantics but reopen applicable decisions for re-review.
x=await call(`/api/styles/${id}/variants`,{method:'POST',body:{code:'MFD-DR-010-DEV2',name:'Requirement development variant',variantKind:'DEVELOPMENT',copyAssets:false,copyColorways:false}});ok(x.r.status===201,'development variant created with requirements');const child=x.data.id;x=await call(`/api/styles/${child}/requirements`);const childReq=x.data.items.find(r=>r.req_key==='CUSTOM:LINING_APPROVAL');ok(childReq&&childReq.applicability==='REQUIRED'&&childReq.status==='OPEN'&&childReq.source==='INHERITED','development variant reopens inherited required decision');
// Audit proof.
x=await call(`/api/audit?orgId=${mohsen.id}`);ok(x.r.status===200&&x.data.items.some(a=>a.action==='REQUIREMENTS_SYNC')&&x.data.items.some(a=>a.entity_type==='REQUIREMENT'&&a.action==='DECISION'),'requirements sync and decisions are audited');
console.log('BATCH10_INTEGRATION_PASS');
