import {readFileSync} from 'node:fs';
import {makeHarness,ok,root} from './test_helpers.mjs';

const {db,env,call,login}=makeHarness();await login();let x=await call('/api/me');const org=x.data.workspaces.find(w=>w.code==='MOHSEN'),admin=db.prepare("SELECT * FROM users WHERE email='dev@sehha.local'").get(),ts=new Date().toISOString();
db.prepare('INSERT INTO users(id,email,display_name,password_hash,password_salt,created_at) VALUES(?,?,?,?,?,?)').run('u_qc','qc@local.test','QC Inspector',admin.password_hash,admin.password_salt,ts);
db.prepare('INSERT INTO memberships(user_id,org_id,role) VALUES(?,?,?)').run('u_qc',org.id,'QC_INSPECTOR');
x=await call('/api/auth/login',{method:'POST',body:{email:'qc@local.test',password:env.DEV_BOOTSTRAP_PASSWORD},cookieOverride:''});const qcCookie=(x.r.headers.get('set-cookie')||'').split(';')[0];ok(x.r.status===200,'QC inspector demo login');
x=await call('/api/styles',{method:'POST',body:{orgId:org.id,code:'QC-HUMAN-01',name:'Guided QC test style',garmentType:'JACKET',audience:'WOMEN',sizingMode:'STANDARD'}});const styleId=x.data.id;
const frozen={style:{id:styleId,org_id:org.id,code:'QC-HUMAN-01',name:'Guided QC test style'},sizeBands:[],colorways:[],measurements:[],bom:[],operations:[],patternPieces:[],patternLinks:[],requirements:[],assets:[],dna:[],gradingRules:[],annotations:[],samples:[],costSheets:[]};
db.prepare('INSERT INTO style_releases(id,style_id,release_no,release_type,status,source_version_no,template_key,gate_json,manifest_json,snapshot_json,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run('qrel',styleId,1,'PRODUCTION','RELEASED',1,'mohsen_nexz_20p','{}','{}',JSON.stringify(frozen),admin.id,ts);
x=await call(`/api/styles/${styleId}/production-lots`,{method:'POST',body:{releaseNo:1,lotCode:'QC-HUMAN-LOT',plannedQty:20}});const lotId=x.data.lot.id;
let y=await call(`/api/human/qc/queue?orgId=${org.id}`,{cookieOverride:qcCookie});ok(y.r.status===200&&y.data.items.length===0,'QC starts with empty truthful queue');
y=await call('/api/human/qc/tasks',{method:'POST',body:{orgId:org.id,lotId,assigneeUserId:'u_qc'},cookieOverride:qcCookie});ok(y.r.status===403,'inspector cannot assign self');
y=await call('/api/human/qc/tasks',{method:'POST',body:{orgId:org.id,lotId,assigneeUserId:'u_qc'}});ok(y.r.status===201,'supervisor grants scoped QC task');const task=y.data.task;
y=await call(`/api/human/qc/queue?orgId=${org.id}`,{cookieOverride:qcCookie});ok(y.data.open===1&&y.data.items[0].id===task.id,'QC sees assigned inspection');
y=await call(`/api/styles/${styleId}/production-lots/${lotId}/release`,{method:'POST',body:{},cookieOverride:qcCookie});ok(y.r.status===403,'QC cannot release production lot');
let body={measurementOk:true,sewingOk:true,visibleDefect:false,expectedVersion:task.lotVersion,requestKey:'qc-pass-001'};
y=await call(`/api/human/qc/tasks/${task.id}/inspections`,{method:'POST',body,cookieOverride:qcCookie});ok(y.r.status===201&&!y.data.defectId,'three-question pass creates canonical QC check');
let repeat=await call(`/api/human/qc/tasks/${task.id}/inspections`,{method:'POST',body,cookieOverride:qcCookie});ok(repeat.r.status===200&&repeat.data.duplicate,'same QC submission is idempotent');
repeat=await call(`/api/human/qc/tasks/${task.id}/inspections`,{method:'POST',body:{...body,visibleDefect:true,defectType:'SEWING',severity:'MINOR'},cookieOverride:qcCookie});ok(repeat.r.status===409,'same key cannot be reused for changed answers');
const png=readFileSync(`${root}/public/demo_jk001_reference.png`),dataUrl=`data:image/png;base64,${png.toString('base64')}`;
y=await call(`/api/human/qc/tasks/${task.id}/photo`,{method:'POST',body:{dataUrl,filename:'qc-evidence.png'},cookieOverride:qcCookie});ok(y.r.status===201&&Boolean(y.data.assetId),'QC photo stored in existing asset/R2 contract');const photoId=y.data.assetId;
body={measurementOk:true,sewingOk:false,visibleDefect:true,defectType:'SEWING',severity:'CRITICAL',photoAssetId:photoId,expectedVersion:y.data.task?.lotVersion??(await call(`/api/human/qc/tasks/${task.id}`,{cookieOverride:qcCookie})).data.task.lotVersion,requestKey:'qc-defect-001'};
y=await call(`/api/human/qc/tasks/${task.id}/inspections`,{method:'POST',body:{...body,photoAssetId:null},cookieOverride:qcCookie});ok(y.r.status===400,'critical defect requires photo evidence');
y=await call(`/api/human/qc/tasks/${task.id}/inspections`,{method:'POST',body,cookieOverride:qcCookie});ok(y.r.status===201&&Boolean(y.data.defectId),'critical sewing defect creates canonical defect');
ok(db.prepare('SELECT COUNT(*) AS n FROM quality_checks WHERE lot_id=?').get(lotId).n===2&&db.prepare('SELECT COUNT(*) AS n FROM production_defects WHERE lot_id=?').get(lotId).n===1,'guided QC writes normal checks and defects');
ok(db.prepare('SELECT asset_id FROM human_defect_evidence WHERE defect_id=?').get(y.data.defectId).asset_id===photoId,'photo linked to exact defect');
repeat=await call(`/api/human/qc/tasks/${task.id}/inspections`,{method:'POST',body,cookieOverride:qcCookie});ok(repeat.r.status===200&&repeat.data.duplicate,'defect and check do not duplicate on retry');
y=await call(`/api/human/qc/tasks/${task.id}/complete`,{method:'POST',body:{},cookieOverride:qcCookie});ok(y.r.status===200&&y.data.task.status==='DONE','inspector completes scoped QC task without release');
y=await call(`/api/human/home?orgId=${org.id}`);ok(y.data.exceptions.some(e=>e.kind==='CRITICAL_DEFECT'&&e.lot_code==='QC-HUMAN-LOT'),'supervisor exception home reflects real critical defect');
console.log('HUMAN_QC_PASS');
