// Local development fixture only. The Wrangler invocation is hardwired to --local.
import {pbkdf2Sync,randomBytes} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {resolve} from 'node:path';

const password=process.env.SEHHA_HUMAN_DEMO_PASSWORD;
if(!password||password.length<12)throw new Error('Set SEHHA_HUMAN_DEMO_PASSWORD to a local demo password of at least 12 characters.');
const q=value=>`'${String(value).replaceAll("'","''")}'`;
const cli=resolve('node_modules/wrangler/bin/wrangler.js');
function localSql(sql){const result=spawnSync(process.execPath,[cli,'d1','execute','DB','--local','--command',sql],{cwd:resolve('.'),encoding:'utf8',maxBuffer:1024*1024});if(result.status!==0)throw new Error((result.stderr||result.stdout||'Local D1 command failed').slice(0,1200));}
const people=[['cutting','Cutting Worker','CUTTING_WORKER'],['sewing','Sewing Operator','SEWING_OPERATOR'],['qc','QC Inspector','QC_INSPECTOR'],['store','Store Clerk','STORE_CLERK'],['supervisor','Factory Supervisor','FACTORY_SUPERVISOR'],['pattern','Pattern Master','PATTERN_MASTER']];
for(const [key,name,role] of people){
  const salt=randomBytes(16).toString('hex'),hash=pbkdf2Sync(password,Buffer.from(salt,'hex'),210000,32,'sha256').toString('hex'),id=`human_demo_${key}`;
  localSql(`INSERT INTO users(id,email,display_name,password_hash,password_salt,is_platform_admin,active,created_at) VALUES(${q(id)},${q(`${key}@human-demo.local`)},${q(name)},${q(hash)},${q(salt)},0,1,datetime('now')) ON CONFLICT(id) DO UPDATE SET password_hash=excluded.password_hash,password_salt=excluded.password_salt,active=1`);
  localSql(`INSERT INTO memberships(user_id,org_id,role) SELECT ${q(id)},id,${q(role)} FROM organizations WHERE code='MOHSEN' ON CONFLICT(user_id,org_id) DO UPDATE SET role=excluded.role`);
}
const styleId='human_demo_style',lotId='human_demo_lot',releaseId='human_demo_release',operationId='human_demo_operation',taskId='human_demo_task';
const snapshot=JSON.stringify({style:{id:styleId,code:'HUMAN-DEMO',name:'تجربة محلية لتسجيل الإنتاج'},sizeBands:[],colorways:[],measurements:[],bom:[],operations:[{seq:1,name:'خياطة الجنب'}],patternPieces:[],patternLinks:[],requirements:[],assets:[],dna:[],gradingRules:[],annotations:[],samples:[],costSheets:[]});
localSql(`INSERT OR IGNORE INTO styles(id,org_id,code,name,garment_type,audience,sizing_mode,status,created_by,created_at,updated_at) SELECT ${q(styleId)},id,'HUMAN-DEMO','تجربة محلية لتسجيل الإنتاج','CUSTOM','UNSPECIFIED','STANDARD','DEVELOPMENT','human_demo_supervisor',datetime('now'),datetime('now') FROM organizations WHERE code='MOHSEN'`);
localSql(`INSERT OR IGNORE INTO style_releases(id,style_id,release_no,release_type,status,source_version_no,template_key,gate_json,manifest_json,snapshot_json,note,created_by,created_at) VALUES(${q(releaseId)},${q(styleId)},1,'PRODUCTION','RELEASED',1,'mohsen_nexz_20p','{}','{}',${q(snapshot)},'LOCAL DEMO ONLY — synthetic fixture','human_demo_supervisor',datetime('now'))`);
localSql(`INSERT OR IGNORE INTO production_lots(id,style_id,release_no,lot_code,planned_qty,status,note,created_by,created_at,updated_at) VALUES(${q(lotId)},${q(styleId)},1,'LOCAL-DEMO-LOT',100,'OPEN','LOCAL DEMO ONLY — synthetic fixture','human_demo_supervisor',datetime('now'),datetime('now'))`);
localSql(`INSERT OR IGNORE INTO production_operation_progress(id,lot_id,operation_seq,operation_name,planned_qty,completed_qty,rejected_qty,status,created_by,updated_by,created_at,updated_at) VALUES(${q(operationId)},${q(lotId)},1,'خياطة الجنب',100,0,0,'NOT_STARTED','human_demo_supervisor','human_demo_supervisor',datetime('now'),datetime('now'))`);
localSql(`INSERT OR IGNORE INTO human_tasks(id,org_id,style_id,lot_id,operation_seq,assignee_user_id,status,created_by,created_at,updated_at) SELECT ${q(taskId)},id,${q(styleId)},${q(lotId)},1,'human_demo_sewing','OPEN','human_demo_supervisor',datetime('now'),datetime('now') FROM organizations WHERE code='MOHSEN'`);
localSql(`INSERT OR IGNORE INTO human_qc_tasks(id,org_id,style_id,lot_id,assignee_user_id,status,created_by,created_at,updated_at) SELECT 'human_demo_qc_task',id,${q(styleId)},${q(lotId)},'human_demo_qc','OPEN','human_demo_supervisor',datetime('now'),datetime('now') FROM organizations WHERE code='MOHSEN'`);
const storeStyle='human_demo_store_style',storeLot='human_demo_store_lot',storeSnapshot=JSON.stringify({...JSON.parse(snapshot),style:{id:storeStyle,code:'HUMAN-STORE-DEMO',name:'تجربة محلية للمخزن'},operations:[]});
const storeBasis=JSON.stringify({available:true,costSheetId:'human_demo_store_cost',currency:'EGP',sourceVersionNo:1,lines:[{sourceType:'BOM',sourceRef:'FABRIC-DEMO',description:'قماش تجريبي',qty:0.5,unit:'m',unitCost:1,wastePct:0}]});
localSql(`INSERT OR IGNORE INTO styles(id,org_id,code,name,garment_type,audience,sizing_mode,status,created_by,created_at,updated_at) SELECT ${q(storeStyle)},id,'HUMAN-STORE-DEMO','تجربة محلية للمخزن','CUSTOM','UNSPECIFIED','STANDARD','DEVELOPMENT','human_demo_supervisor',datetime('now'),datetime('now') FROM organizations WHERE code='MOHSEN'`);
localSql(`INSERT OR IGNORE INTO style_releases(id,style_id,release_no,release_type,status,source_version_no,template_key,gate_json,manifest_json,snapshot_json,note,created_by,created_at) VALUES('human_demo_store_release',${q(storeStyle)},1,'PRODUCTION','RELEASED',1,'mohsen_nexz_20p','{}','{}',${q(storeSnapshot)},'LOCAL DEMO ONLY — synthetic fixture','human_demo_supervisor',datetime('now'))`);
localSql(`INSERT OR IGNORE INTO cost_sheets(id,style_id,version_no,name,currency,status,labor_cost,overhead_pct,waste_pct,created_by,approved_by,created_at,updated_at,approved_at) VALUES('human_demo_store_cost',${q(storeStyle)},1,'Local approved demo material','EGP','APPROVED',0,0,0,'human_demo_supervisor','human_demo_supervisor',datetime('now'),datetime('now'),datetime('now'))`);
localSql(`INSERT OR IGNORE INTO cost_lines(id,cost_sheet_id,source_type,source_ref,description,qty,unit,unit_cost,waste_pct,line_total,created_by,updated_by,created_at,updated_at) VALUES('human_demo_store_line','human_demo_store_cost','BOM','FABRIC-DEMO','قماش تجريبي',0.5,'m',1,0,0.5,'human_demo_supervisor','human_demo_supervisor',datetime('now'),datetime('now'))`);
localSql(`INSERT OR IGNORE INTO production_lots(id,style_id,release_no,lot_code,planned_qty,status,note,planning_basis_json,created_by,created_at,updated_at) VALUES(${q(storeLot)},${q(storeStyle)},1,'LOCAL-STORE-LOT',100,'OPEN','LOCAL DEMO ONLY — synthetic fixture',${q(storeBasis)},'human_demo_supervisor',datetime('now'),datetime('now'))`);
localSql(`INSERT OR IGNORE INTO human_store_balances(lot_id,org_id,style_id,material_key,unit) SELECT ${q(storeLot)},id,${q(storeStyle)},'REF:FABRIC-DEMO','m' FROM organizations WHERE code='MOHSEN'`);
for(const movement of ['RECEIVE','ISSUE','RETURN'])localSql(`INSERT OR IGNORE INTO human_store_tasks(id,org_id,style_id,lot_id,material_key,source_ref,description,unit,movement,assignee_user_id,status,created_by,created_at,updated_at) SELECT ${q(`human_demo_store_${movement.toLowerCase()}`)},id,${q(storeStyle)},${q(storeLot)},'REF:FABRIC-DEMO','FABRIC-DEMO','قماش تجريبي','m',${q(movement)},'human_demo_store','OPEN','human_demo_supervisor',datetime('now'),datetime('now') FROM organizations WHERE code='MOHSEN'`);
console.log('Local human demo ready: cutting, sewing, qc, store, supervisor, pattern @human-demo.local. Synthetic sewing, QC, and store tasks use LOCAL-DEMO lots.');
