// First-class engineering records. Calculations are proposals until their inputs are approved.
import {FactorySpreadsheetImporter,parseCsv,exportCsv} from './spreadsheet_adapter.js';
import {composeEngineeringTechPack} from './techpack_composer.js';
const DOMAIN = {
  fabrics: {table:'fabric_specifications',prefix:'fab_',fields:['name_ar','name_en','composition','construction','structure','gsm','width_cm','usable_width_cm','stretch_x_pct','stretch_y_pct','shrinkage_warp_pct','shrinkage_weft_pct','finish','color','supplier','lot','roll','nap','direction_rule','repeat_x_cm','repeat_y_cm','matching_required','defect_allowance_pct','purchase_unit','cutting_unit','source','state'],required:['name_en'],numbers:['gsm','width_cm','usable_width_cm','stretch_x_pct','stretch_y_pct','shrinkage_warp_pct','shrinkage_weft_pct','repeat_x_cm','repeat_y_cm','defect_allowance_pct']},
  trims: {table:'trim_specifications',prefix:'trm_',fields:['trim_type','name_ar','name_en','supplier','size','color','material','placement','quantity','wastage_pct','unit','asset_id','note','source','state'],required:['trim_type','name_en'],numbers:['quantity','wastage_pct']},
  patterns: {table:'pattern_piece_specs',prefix:'ppc_',fields:['name_ar','name_en','size_code','cut_qty','material_code','grain_direction','nap_direction','seam_allowance_cm','notches_json','annotations_json','points_json','edges_json','mirror_rule','pair_rule','fold_line','source','state'],required:['name_en'],numbers:['cut_qty','seam_allowance_cm'],json:['notches_json','annotations_json','points_json','edges_json']},
  markers: {table:'marker_plans',prefix:'mrk_',fields:['fabric_code','size_ratio_json','marker_length_m','marker_width_cm','usable_width_cm','efficiency_pct','plies','wastage_pct','layout_json','source','state'],required:['fabric_code'],numbers:['marker_length_m','marker_width_cm','usable_width_cm','efficiency_pct','plies','wastage_pct'],json:['size_ratio_json','layout_json']},
  routing: {table:'routing_steps',prefix:'rte_',fields:['sequence_no','department','name_ar','name_en','machine','attachment','stitch_type','spi','seam_type','folder','gauge','presser_foot','operator_skill','smv','sam','qc_checkpoint','predecessor_code','parallel_code','reference_asset_id','source','state'],required:['sequence_no','department','name_en'],numbers:['sequence_no','spi','smv','sam']},
  stages: {table:'factory_stages',prefix:'stg_',fields:['sequence_no','owner_user_id','status','started_at','completed_at','comment','approval','rejection_reason','source'],required:['sequence_no'],numbers:['sequence_no']}
};
const idFields=['brand','customer','season','collection','gender','category','subcategory','owner_user_id','approved_by','state'];
const states=new Set(['DRAFT','SUGGESTED','TBC','APPROVED','REJECTED']);
const approvalFields={fabrics:['name_en','composition','construction','width_cm','usable_width_cm','purchase_unit','cutting_unit'],trims:['trim_type','name_en','placement','quantity','unit'],patterns:['name_en','cut_qty','material_code','grain_direction','seam_allowance_cm'],markers:['fabric_code','size_ratio_json','marker_length_m','usable_width_cm','plies','layout_json'],routing:['sequence_no','department','name_en','machine']};
const stageStatuses=new Set(['NOT_STARTED','IN_PROGRESS','COMPLETE','APPROVED','REJECTED','BLOCKED','NOT_APPLICABLE']);
const ownerRoles=new Set(['PLATFORM_ADMIN','PLATFORM_OWNER','WORKSPACE_OWNER']);
function assertApprovalRole(role,domain,code){if(ownerRoles.has(role))return;const allowed=domain==='routing'?['FACTORY_SUPERVISOR','PRODUCTION']:domain==='patterns'||domain==='identity'||domain==='fabrics'||domain==='trims'||domain==='markers'?['DESIGN_PATTERN_MASTER']:domain==='stages'?(code==='RELEASE'?['RELEASE_MANAGER']:code.endsWith('_QC')?['QC_MANAGER']:['FACTORY_SUPERVISOR','PRODUCTION']):[];if(!allowed.includes(role))throw errors(`Role ${role} cannot approve ${domain}/${code}`,403);}
export const FACTORY_STAGE_CODES=['STYLE_RECEIVED','TECHNICAL_REVIEW','SAMPLE_DEVELOPMENT','PATTERN','PATTERN_APPROVAL','FABRIC_APPROVAL','TRIM_APPROVAL','SAMPLE_CUTTING','SAMPLE_SEWING','FIT_REVIEW','MEASUREMENT_REVIEW','PATTERN_CORRECTION','PP_SAMPLE','PP_APPROVAL','SIZE_SET','MARKER','FABRIC_CONSUMPTION','FABRIC_BOOKING','CUTTING_ORDER','SPREADING','CUTTING','BUNDLING','SEWING_INPUT','SEWING','INLINE_QC','ENDLINE_QC','FINISHING','PRESS','FINAL_QC','PACKING','RELEASE'];
const errors=(message,status=400)=>Object.assign(new Error(message),{status});
const response=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const read=(env,sql,...values)=>env.DB.prepare(sql).bind(...values).first();
const all=async(env,sql,...values)=>(await env.DB.prepare(sql).bind(...values).all()).results||[];
const write=(env,sql,...values)=>env.DB.prepare(sql).bind(...values).run();
const stamp=()=>new Date().toISOString();
const identifier=(prefix)=>prefix+crypto.randomUUID();
const keyOf=(value)=>{const key=String(value||'').trim().toUpperCase();if(!/^[A-Z0-9][A-Z0-9._-]{0,59}$/.test(key))throw errors('Code must be 1–60 Latin letters, digits, dot, dash or underscore');return key;};
function parseValue(field,value,config){
  if(value==null||value==='')return null;
  if(config.numbers?.includes(field)){const n=Number(value);if(!Number.isFinite(n)||n<0||n>1000000)throw errors(`${field} must be a finite non-negative number`);if(['cut_qty','plies','sequence_no'].includes(field)&&(!Number.isInteger(n)||n===0))throw errors(`${field} must be a positive integer`);if(field.endsWith('_pct')&&n>100)throw errors(`${field} must be between 0 and 100`);return n;}
  if(config.json?.includes(field)){const expected=field==='size_ratio_json'||field==='layout_json'?'object':'array';if(typeof value!=='object'||value===null||Array.isArray(value)!==(expected==='array'))throw errors(`${field} must be ${expected}`);const encoded=JSON.stringify(value);if(encoded.length>50000)throw errors(`${field} exceeds 50 KB`);return encoded;}
  if(field==='matching_required')return value===true||value===1||value==='1'?1:0;
  const s=String(value).trim();if(s.length>5000)throw errors(`${field} exceeds 5000 characters`);return s;
}
function canonical(body,config){const data={};for(const field of config.fields){const camel=field.replace(/_([a-z])/g,(_,c)=>c.toUpperCase());if(Object.hasOwn(body,field)||Object.hasOwn(body,camel)){const raw=Object.hasOwn(body,field)?body[field]:body[camel];data[field]=parseValue(field,raw,config);}}if(data.state!=null&&!states.has(data.state))throw errors('state must be DRAFT, SUGGESTED, TBC, APPROVED or REJECTED');if(config.fields.includes('source')&&data.source==null)data.source='MANUAL';if(data.state==null&&config.fields.includes('state'))data.state='DRAFT';return data;}
function materialRequirement(marker,fabric,quantity){
  if(!fabric)return {status:'BLOCKED',reason:'Fabric specification missing'};
  const ratio=JSON.parse(marker.size_ratio_json||'{}');const garmentsPerLay=Object.values(ratio).reduce((sum,n)=>sum+Number(n),0);
  if(!garmentsPerLay||!Number.isInteger(garmentsPerLay)||Object.values(ratio).some(n=>!Number.isInteger(Number(n))||Number(n)<0))return {status:'TBC',reason:'Valid size ratio required'};
  const length=Number(marker.marker_length_m),plies=Number(marker.plies),qty=Number(quantity);
  if(!(length>0&&plies>0&&Number.isInteger(plies)&&qty>0&&Number.isInteger(qty)&&qty<=10000000))return {status:'TBC',reason:'Marker length, plies and production quantity required'};
  if(Number(marker.usable_width_cm)>Number(fabric.usable_width_cm)||!fabric.usable_width_cm)return {status:'BLOCKED',reason:'Marker usable width exceeds fabric usable width or fabric width is TBC'};
  if(fabric.direction_rule==='ONE_WAY'&&JSON.parse(marker.layout_json||'{}').direction!=='ONE_WAY')return {status:'BLOCKED',reason:'One-way fabric requires a one-way marker layout'};
  const garmentsPerMarker=garmentsPerLay*plies,markers=Math.ceil(qty/garmentsPerMarker),net=markers*length*plies;
  const waste=Number(marker.wastage_pct||0),shrink=Number(fabric.shrinkage_warp_pct||0),defect=Number(fabric.defect_allowance_pct||0);
  const purchase=net*(1+waste/100)*(1+defect/100)/(1-shrink/100);
  if(!Number.isFinite(purchase))return {status:'BLOCKED',reason:'Shrinkage must be below 100%'};
  return {status:'CALCULATED',approval:'REQUIRES_REVIEW',garmentsPerLay,garmentsPerMarker,markers,netMeters:net,wasteMeters:net*waste/100,plannedMeters:purchase,purchaseMeters:purchase,assumptions:{wastagePct:waste,defectAllowancePct:defect,shrinkageWarpPct:shrink}};
}
function routingValidation(steps){const errors=[];const byCode=new Map(steps.map(x=>[x.code,x]));for(const row of steps){if(row.predecessor_code&&!byCode.has(row.predecessor_code))errors.push(`${row.code}: predecessor missing`);if(row.predecessor_code&&byCode.has(row.predecessor_code)&&Number(byCode.get(row.predecessor_code).sequence_no)>=Number(row.sequence_no))errors.push(`${row.code}: predecessor order conflict`);if(row.predecessor_code===row.code)errors.push(`${row.code}: self predecessor`);if(!row.machine)errors.push(`${row.code}: machine TBC`);}return {ready:errors.length===0,errors};}
function readiness(bundle){const blockers=[];const add=(condition,code)=>{if(condition)blockers.push(code)};const s=bundle.style,measurements=bundle.measurements||[],patterns=bundle.patterns||[],fabrics=bundle.fabrics||[],trims=bundle.trims||[],markers=bundle.markers||[],routing=bundle.routing||[],samples=bundle.samples||[];
  add(!s.base_size,'BASE_SIZE_TBC');add(!measurements.length||measurements.some(x=>x.value==null||!['APPROVED','LOCKED'].includes(x.state)||x.tolerance_plus==null||x.tolerance_minus==null),'MEASUREMENTS_UNAPPROVED_OR_INCOMPLETE');
  add(!patterns.length||patterns.some(x=>x.state!=='APPROVED'),'PATTERN_UNAPPROVED');add(!fabrics.length||fabrics.some(x=>x.state!=='APPROVED'),'FABRIC_UNAPPROVED');add(!trims.length||trims.some(x=>x.state!=='APPROVED'),'TRIMS_UNAPPROVED');
  add(!(bundle.bom||[]).length||(bundle.bom||[]).some(x=>x.status!=='APPROVED'||x.qty==null),'BOM_INCOMPLETE');add(!markers.length||markers.some(x=>x.state!=='APPROVED'||materialRequirement(x,fabrics.find(f=>f.code===x.fabric_code),1).status!=='CALCULATED'),'MARKER_OR_CONSUMPTION_UNAPPROVED');add(!routing.length||routing.some(x=>x.state!=='APPROVED')||!routingValidation(routing).ready,'ROUTING_UNAPPROVED');
  add(!samples.some(x=>x.sample_type==='PP'&&x.status==='APPROVED'),'PP_SAMPLE_UNAPPROVED');add(!routing.some(x=>x.qc_checkpoint),'QC_PLAN_MISSING');
  const tbc=(bundle.dna||[]).filter(x=>/\bTBC\b|UNKNOWN/i.test(String(x.value_text||''))||x.provenance==='UNKNOWN');add(tbc.length>0,'CRITICAL_TBC_OPEN');
  return {status:blockers.length?'BLOCKED':'ELIGIBLE_FOR_MANUAL_RELEASE_REVIEW',percent:Math.round((11-blockers.length)/11*100),blockers};
}
async function bundleFor(env,style){const id=style.id;const [identity,fabrics,trims,patterns,markers,routing,stages,measurements,bom,dna,samples,revisions]=await Promise.all([
  read(env,'SELECT * FROM style_identity WHERE style_id=?',id),all(env,'SELECT * FROM fabric_specifications WHERE style_id=? ORDER BY code',id),all(env,'SELECT * FROM trim_specifications WHERE style_id=? ORDER BY code',id),all(env,'SELECT * FROM pattern_piece_specs WHERE style_id=? ORDER BY code,size_code',id),all(env,'SELECT * FROM marker_plans WHERE style_id=? ORDER BY code',id),all(env,'SELECT * FROM routing_steps WHERE style_id=? ORDER BY sequence_no',id),all(env,'SELECT * FROM factory_stages WHERE style_id=? ORDER BY sequence_no',id),all(env,'SELECT * FROM measurements WHERE style_id=? ORDER BY sort_order,code',id),all(env,'SELECT * FROM bom_items WHERE style_id=? ORDER BY sort_order,code',id),all(env,'SELECT * FROM dna_items WHERE style_id=? ORDER BY field_key',id),all(env,'SELECT * FROM sample_rounds WHERE style_id=? ORDER BY round_no DESC',id),all(env,'SELECT * FROM engineering_revisions WHERE style_id=? ORDER BY created_at DESC LIMIT 100',id)]);
  const b={style,identity,fabrics,trims,patterns,markers,routing,stages,measurements,bom,dna,samples,revisions};b.readiness=readiness(b);b.routingValidation=routingValidation(routing);return b;}
async function recordRevision(env,ctx,style,domain,key,oldValue,newValue,reason,revision){await write(env,'INSERT INTO engineering_revisions(id,style_id,domain,record_key,revision,old_json,new_json,reason,user_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',identifier('rev_'),style.id,domain,key,revision,oldValue?JSON.stringify(oldValue):null,JSON.stringify(newValue),reason||null,ctx.userId,stamp());await ctx.audit(env,style.org_id,ctx.userId,'ENGINEERING',style.id,'UPSERT',{domain,key,revision});}
async function upsert(env,ctx,style,domain,key,body){const spec=DOMAIN[domain],table=spec.table,data=canonical(body,spec);if(domain==='patterns'&&data.size_code)data.size_code=String(data.size_code).toUpperCase();const existing=domain==='patterns'?await read(env,`SELECT * FROM ${table} WHERE style_id=? AND code=? AND COALESCE(size_code,'')=?`,style.id,key,data.size_code||''):await read(env,`SELECT * FROM ${table} WHERE style_id=? AND code=?`,style.id,key);for(const required of spec.required)if((data[required]??existing?.[required])==null)throw errors(`${required} required`);
  if(existing?.state==='APPROVED'&&(!body.revisionReason||String(body.revisionReason).trim().length<5))throw errors('Approved record requires revisionReason of at least five characters',409);
  if(domain==='stages'&&data.status&&!stageStatuses.has(data.status))throw errors('Invalid factory stage status');
  if(data.state==='APPROVED'||domain==='stages'&&['COMPLETE','APPROVED'].includes(data.status)){const role=await ctx.membershipRole(env,ctx.session,style.org_id);assertApprovalRole(role,domain,key);}
  if(domain==='stages'&&data.status==='REJECTED'&&!String(data.rejection_reason||existing?.rejection_reason||'').trim())throw errors('Rejection reason required');
  if(domain==='stages'&&data.status==='IN_PROGRESS'&&!data.started_at&&!existing?.started_at)data.started_at=stamp();
  if(domain==='stages'&&['COMPLETE','APPROVED'].includes(data.status)&&!data.completed_at&&!existing?.completed_at)data.completed_at=stamp();
  if(data.state==='APPROVED'){const merged={...existing,...data};const missing=(approvalFields[domain]||[]).filter(field=>merged[field]==null||merged[field]===''||/\bTBC\b|UNKNOWN|NOT PROVIDED/i.test(String(merged[field])));if(missing.length)throw errors(`Cannot approve ${domain}; complete: ${missing.join(', ')}`);}
  if(domain==='markers'){const fabric=await read(env,'SELECT * FROM fabric_specifications WHERE style_id=? AND code=?',style.id,data.fabric_code||existing?.fabric_code);if(!fabric)throw errors('Fabric code must exist in this style');}
  if(domain==='markers'&&data.state==='APPROVED'){const fabric=await read(env,'SELECT * FROM fabric_specifications WHERE style_id=? AND code=?',style.id,data.fabric_code||existing?.fabric_code),calculation=materialRequirement({...existing,...data},fabric,1);if(fabric.state!=='APPROVED'||calculation.status!=='CALCULATED')throw errors(`Marker approval blocked: ${calculation.reason||'fabric not approved'}`);}
  if(domain==='patterns'&&data.material_code){const fabric=await read(env,'SELECT code FROM fabric_specifications WHERE style_id=? AND code=?',style.id,data.material_code);if(!fabric)throw errors('Pattern material code must exist in this style');}
  if(domain==='routing'&&data.predecessor_code===key)throw errors('Routing step cannot precede itself');
  const revision=(existing?.revision||0)+1,ts=stamp(),recordId=existing?.id||identifier(spec.prefix);if(existing){if(existing.state==='APPROVED')data.state='DRAFT';const fields=Object.keys(data);await write(env,`UPDATE ${table} SET ${fields.map(x=>`${x}=?`).join(',')}, revision=?, updated_at=? WHERE id=?`,...fields.map(x=>data[x]),revision,ts,recordId);}else{const fields=['id','style_id','code',...Object.keys(data),'revision','created_at','updated_at'],values=[recordId,style.id,key,...Object.values(data),revision,ts,ts];await write(env,`INSERT INTO ${table}(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')})`,...values);}
  const updated=await read(env,`SELECT * FROM ${table} WHERE id=?`,recordId);await recordRevision(env,ctx,style,domain,domain==='patterns'?`${key}:${updated.size_code||'TBC'}`:key,existing,updated,body.revisionReason,revision);return updated;}
export async function engineeringRoute(request,env,ctx){const url=new URL(request.url),match=url.pathname.match(/^\/api\/styles\/([^/]+)\/engineering(?:\/([^/]+)(?:\/([^/]+))?)?$/);if(!match)return null;
  const session=await ctx.requireAuth(request,env),style=await read(env,'SELECT * FROM styles WHERE id=?',match[1]);if(!style)return response({error:'Style not found'},404);await ctx.requireOrg(env,session,style.org_id);
  const domain=match[2],key=match[3]&&keyOf(decodeURIComponent(match[3]));if(request.method==='GET'&&!domain)return response(await bundleFor(env,style));
  if(request.method==='GET'&&domain==='techpack'){const language=url.searchParams.get('lang')||'bilingual';if(!['ar','en','bilingual'].includes(language))throw errors('lang must be ar, en or bilingual');const document=composeEngineeringTechPack(await bundleFor(env,style),{language});return new Response(document,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});}
  if(request.method==='POST'&&domain==='stages'&&key==='INITIALIZE'){let created=0;for(const [index,code] of FACTORY_STAGE_CODES.entries()){const existing=await read(env,'SELECT id FROM factory_stages WHERE style_id=? AND code=?',style.id,code);if(existing)continue;const slot=await read(env,'SELECT code FROM factory_stages WHERE style_id=? AND sequence_no=?',style.id,index+1);if(slot)continue;const ts=stamp();await write(env,'INSERT INTO factory_stages(id,style_id,code,sequence_no,status,source,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',identifier('stg_'),style.id,code,index+1,'NOT_STARTED','TEMPLATE',1,ts,ts);created++;}await ctx.audit(env,style.org_id,session.userId,'FACTORY_WORKFLOW',style.id,'INITIALIZE',{created});return response({created,total:FACTORY_STAGE_CODES.length,items:await all(env,'SELECT * FROM factory_stages WHERE style_id=? ORDER BY sequence_no',style.id)});}
  if(request.method==='POST'&&domain==='import-preview'){const body=await ctx.requestBody(request),spec=DOMAIN[body.domain];if(!spec||body.domain==='stages')throw errors('Unsupported import domain');try{const allowed=spec.fields.flatMap(x=>[x,x.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]);const importer=new FactorySpreadsheetImporter({mapping:body.mapping,required:['code',...spec.required.map(x=>body.mapping?.[x]?x:x.replace(/_([a-z])/g,(_,c)=>c.toUpperCase()))],allowedFields:allowed});const rows=body.format==='CSV'?parseCsv(body.csv):body.format==='JSON'?body.rows:null;if(!rows)throw errors('format must be CSV or JSON');return response(importer.stage(rows));}catch(e){throw errors(e.message);}}
  if(request.method==='GET'&&domain==='export'){const exportDomain=url.searchParams.get('domain'),spec=DOMAIN[exportDomain],format=String(url.searchParams.get('format')||'JSON').toUpperCase();if(!spec)throw errors('Unsupported export domain');const rows=await all(env,`SELECT * FROM ${spec.table} WHERE style_id=? ORDER BY code`,style.id);if(format==='JSON')return response({styleCode:style.code,domain:exportDomain,items:rows});if(format==='CSV'){const fields=['code',...spec.fields],content=exportCsv(rows,fields);return new Response(content,{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="${exportDomain}.csv"`,'cache-control':'no-store'}});}throw errors('format must be JSON or CSV');}
  if(request.method==='GET'&&domain==='consumption'){const marker=await read(env,'SELECT * FROM marker_plans WHERE style_id=? AND code=?',style.id,key||'');if(!marker)return response({error:'Marker not found'},404);const fabric=await read(env,'SELECT * FROM fabric_specifications WHERE style_id=? AND code=?',style.id,marker.fabric_code);return response(materialRequirement(marker,fabric,Number(url.searchParams.get('quantity'))));}
  if(request.method==='PUT'&&domain==='identity'&&!key){const body=await ctx.requestBody(request),data=canonical(body,{fields:idFields}),existing=await read(env,'SELECT * FROM style_identity WHERE style_id=?',style.id);if(data.state==='APPROVED')assertApprovalRole(await ctx.membershipRole(env,session,style.org_id),'identity',style.code);if(existing?.state==='APPROVED'&&(!body.revisionReason||String(body.revisionReason).trim().length<5))throw errors('Approved identity requires revisionReason',409);if(existing?.state==='APPROVED')data.state='DRAFT';const rev=(existing?.revision||0)+1,ts=stamp();if(existing){const fields=Object.keys(data);await write(env,`UPDATE style_identity SET ${fields.map(x=>`${x}=?`).join(',')},revision=?,updated_at=? WHERE style_id=?`,...fields.map(x=>data[x]),rev,ts,style.id);}else{const fields=['style_id',...Object.keys(data),'revision','created_at','updated_at'];await write(env,`INSERT INTO style_identity(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')})`,style.id,...Object.values(data),rev,ts,ts);}const updated=await read(env,'SELECT * FROM style_identity WHERE style_id=?',style.id);await recordRevision(env,{...ctx,userId:session.userId},style,'identity',style.code,existing,updated,body.revisionReason,rev);return response(updated);}
  if(request.method==='PUT'&&DOMAIN[domain]&&key){const body=await ctx.requestBody(request),updated=await upsert(env,{...ctx,userId:session.userId,session},style,domain,key,body);return response(updated);}
  return response({error:'Engineering route not found'},404);
}
export {materialRequirement,routingValidation,readiness};
