const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shown=x=>x==null||x===''?'TBC':esc(x);
const chunks=(rows,size=17)=>Array.from({length:Math.ceil(rows.length/size)},(_,i)=>rows.slice(i*size,(i+1)*size));
const table=(head,rows)=>`<table><thead><tr>${head.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${shown(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
export function composeEngineeringTechPack(bundle,{language='bilingual'}={}){
  const s=bundle.style,identity=bundle.identity||{},sections=[];if(!['ar','en','bilingual'].includes(language))throw new Error('Unsupported language');
  const bilingual=language==='bilingual',title=(ar,en)=>language==='ar'?ar:language==='en'?en:`${ar} / ${en}`;
  const add=(key,heading,header,rows)=>{for(const [i,chunk] of chunks(rows).entries())sections.push({key,heading:i?`${heading} (${i+1})`:heading,body:table(header,chunk)});};
  sections.push({key:'cover',heading:title('سجل المنتج الهندسي','Engineering Product Record'),body:`<div class="cover"><h1>${esc(s.code)}</h1><h2>${esc(s.name)}</h2><dl><dt>${title('نوع المنتج','Garment')}</dt><dd>${shown(s.garment_type)}</dd><dt>${title('العلامة','Brand')}</dt><dd>${shown(identity.brand)}</dd><dt>${title('العميل','Customer')}</dt><dd>${shown(identity.customer)}</dd><dt>${title('الموسم','Season')}</dt><dd>${shown(identity.season)}</dd><dt>${title('المقاس الأساسي','Base size')}</dt><dd>${shown(s.base_size)}</dd><dt>${title('المراجعة','Revision')}</dt><dd>${shown(identity.revision)}</dd></dl><p class="warning">${title('أي بند TBC أو غير معتمد يحتاج مراجعة قبل الإنتاج.','TBC or unapproved items require review before production.')}</p></div>`});
  if(bundle.measurements?.length)add('measurements',title('القياسات','Measurements'),[title('الكود','Code'),title('الاسم','Name'),title('القيمة','Value'),title('الوحدة','Unit'),title('السماحية + / -','Tolerance + / -'),title('الحالة','State')],bundle.measurements.map(x=>[x.code,bilingual?`${x.name} / ${x.name_en||'TBC'}`:language==='ar'?x.name:x.name_en||'TBC',x.value,x.unit,`${x.tolerance_plus??'TBC'} / ${x.tolerance_minus??'TBC'}`,x.state]));
  if(bundle.fabrics?.length)add('fabrics',title('القماش','Fabric'),[title('الكود','Code'),title('الاسم','Name'),title('التركيب','Composition'),title('العرض الصالح','Usable width cm'),title('الاتجاه','Direction'),title('الحالة','State')],bundle.fabrics.map(x=>[x.code,bilingual?`${x.name_ar||'TBC'} / ${x.name_en}`:language==='ar'?x.name_ar:x.name_en,x.composition,x.usable_width_cm,x.direction_rule,x.state]));
  if(bundle.trims?.length)add('trims',title('المستلزمات','Trims'),[title('الكود','Code'),title('النوع','Type'),title('الاسم','Name'),title('الكمية','Qty'),title('الموضع','Placement'),title('الحالة','State')],bundle.trims.map(x=>[x.code,x.trim_type,bilingual?`${x.name_ar||'TBC'} / ${x.name_en}`:language==='ar'?x.name_ar:x.name_en,x.quantity,x.placement,x.state]));
  if(bundle.bom?.length)add('bom',title('قائمة المواد','Bill of Materials'),[title('الكود','Code'),title('الفئة','Category'),title('الاسم','Name'),title('الكمية','Qty'),title('الوحدة','Unit'),title('الحالة','State')],bundle.bom.map(x=>[x.code,x.category,bilingual?`${x.name} / ${x.name_en||'TBC'}`:language==='ar'?x.name:x.name_en,x.qty,x.unit,x.status]));
  if(bundle.patterns?.length)add('patterns',title('قطع الباترون','Pattern pieces'),[title('الكود','Code'),title('الاسم','Name'),title('المقاس','Size'),title('القص','Cut qty'),title('اتجاه الخيط','Grain'),title('سماحية الخياطة','Seam allowance cm'),title('الحالة','State')],bundle.patterns.map(x=>[x.code,bilingual?`${x.name_ar||'TBC'} / ${x.name_en}`:language==='ar'?x.name_ar:x.name_en,x.size_code,x.cut_qty,x.grain_direction,x.seam_allowance_cm,x.state]));
  if(bundle.markers?.length)add('markers',title('الماركر','Markers'),[title('الكود','Code'),title('القماش','Fabric'),title('نسبة المقاسات','Size ratio'),title('الطول م','Length m'),title('العرض الصالح سم','Usable width cm'),title('الحالة','State')],bundle.markers.map(x=>[x.code,x.fabric_code,x.size_ratio_json,x.marker_length_m,x.usable_width_cm,x.state]));
  if(bundle.routing?.length)add('routing',title('نشرة التشغيل','Operation bulletin'),[title('الترتيب','Seq'),title('الكود','Code'),title('القسم','Department'),title('العملية','Operation'),title('الماكينة','Machine'),title('الدقائق','SMV'),title('فحص الجودة','QC'),title('الحالة','State')],bundle.routing.map(x=>[x.sequence_no,x.code,x.department,bilingual?`${x.name_ar||'TBC'} / ${x.name_en}`:language==='ar'?x.name_ar:x.name_en,x.machine,x.smv,x.qc_checkpoint,x.state]));
  if(bundle.stages?.length)add('workflow',title('مراحل المصنع','Factory workflow'),[title('الترتيب','Seq'),title('المرحلة','Stage'),title('الحالة','Status'),title('الاعتماد','Approval'),title('الملاحظة','Comment')],bundle.stages.map(x=>[x.sequence_no,x.code,x.status,x.approval,x.comment]));
  const total=sections.length,dir=language==='en'?'ltr':'rtl';return `<!doctype html><html lang="${language==='ar'?'ar':'en'}" dir="${dir}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(s.code)} — Engineering Tech Pack</title><style>@page{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0;background:#ecebe8;color:#1d2b33;font:12px 'Segoe UI',Tahoma,Arial,sans-serif}.page{width:210mm;min-height:297mm;background:#fff;margin:8mm auto;position:relative;padding:18mm 14mm 17mm;break-after:page;page-break-after:always;box-shadow:0 3px 18px #0002}.page:last-child{break-after:auto;page-break-after:auto}.header{border-bottom:2px solid #153c3a;padding-bottom:4mm;display:flex;justify-content:space-between;gap:8mm}.brand{font-weight:900;font-size:17px;color:#153c3a}.meta{color:#596b70;font-size:10px}.page h1{font-size:22px;margin:9mm 0 5mm;color:#153c3a}.cover h1{font-size:42px;margin:18mm 0 1mm}.cover h2{font-size:25px;margin:0 0 12mm}.cover dl{display:grid;grid-template-columns:40mm 1fr;gap:3mm;border-top:1px solid #ccd4d3;padding-top:6mm}.cover dt{color:#53666c}.cover dd{margin:0;font-weight:700}.warning{padding:4mm;background:#fff5d9;border:1px solid #e8d095;margin-top:12mm}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1px solid #c8d2d1;padding:2mm;vertical-align:top;overflow-wrap:anywhere}th{background:#e9f1ef;color:#153c3a}.footer{position:absolute;inset:auto 14mm 8mm;display:flex;justify-content:space-between;border-top:1px solid #c8d2d1;padding-top:2mm;color:#66777d;font-size:9px}.print{position:fixed;inset:10px 10px auto auto;z-index:2;background:#153c3a;color:#fff;border:0;border-radius:6px;padding:9px 14px;cursor:pointer}@media print{body{background:#fff}.page{margin:0;box-shadow:none}.print{display:none}}@media screen and (max-width:800px){.page{width:100%;min-height:0;margin:0 0 8px;padding:20px 14px 42px;overflow-x:auto}.footer{position:static;margin-top:20px}.cover h1{font-size:32px}}</style></head><body><button class="print" onclick="print()">${title('طباعة / حفظ PDF','Print / Save PDF')}</button>${sections.map((page,i)=>`<section class="page"><div class="header"><div class="brand">SEHHA ApparelOS</div><div class="meta">${esc(s.code)} · Rev ${shown(identity.revision)} · ${shown(s.garment_type)}</div></div><h1>${page.heading}</h1>${page.body}<div class="footer"><span>${esc(s.code)} · ${title('سجل هندسي','Engineering record')}</span><span>${i+1} / ${total}</span></div></section>`).join('')}</body></html>`;
}
